# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ".\api\api.csproj" --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(80998369-c8f1-4952-8e08-afdabc987a6c)'
    appType: 'webApp'
    WebAppName: 'ba'
    deployToSlotOrASE: true
    ResourceGroupName: 'DefaultResourceGroup'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/api/bin/release/net6.0'